DigiDNA April 2021 tweaks
ProfileCreator/ProfileManifests pull request #428
Opened 2021-04-01 09:45 UTC by relgit

This PR contains two housekeeping items:

- Redundant keys removed in certain property dictionaries
- `ManagedFavorites` structure updated in Chromium-based browser manifests

2021-04-03 16:46 UTC, apizz approved these changes
All look good to me.  Thanks for adding / fixing the toplevel_name for the bookmark folder

2021-04-03 16:50 UTC, apizz requested changes
Sorry, missed that Edge did not have a pfm_version bump.  That one change should be good to merge

2021-04-03 16:50 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.microsoft.Edge.plist
> +	<date>2021-04-01T09:24:39Z</date>
Should bump the pfm_version of Edge like you did for Chrome & Brave

2021-06-03 05:19 UTC, apizz requested changes
Very small tweak

2021-06-03 05:19 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.microsoft.Edge.plist
> +							<string>toplevel_name</string>
Can we add a more user-friendly `pfm_title` for this?

2021-07-22 04:08 UTC, apizz commented
Need to address the conflicting files

2021-08-10 09:44 UTC, relgit commented
> Need to address the conflicting files

Done.

2021-09-19 15:56 UTC, merged