DigiDNA MCX Guest Account
ProfileCreator/ProfileManifests pull request #523
Opened 2022-02-14 14:54 UTC by relgit

Added the keys on the MCX Guest Account subdomain.

2022-02-14 20:19 UTC, kevinmcox requested changes
Can you add in `pfm_documentation_url` and `pfm_macos_min` for each of the keys?

2022-02-14 20:19 UTC, kevinmcox commented on Manifests/ManifestsApple/com.apple.MCX-GuestAccount.plist
> +			<key>pfm_name</key>
<key>pfm_documentation_url</key>
			<string>https://developer.apple.com/documentation/devicemanagement/accounts</string>
			<key>pfm_macos_min</key>
			<string>10.7</string>

2022-02-14 20:19 UTC, kevinmcox commented on Manifests/ManifestsApple/com.apple.MCX-GuestAccount.plist
> +			<key>pfm_name</key>
<key>pfm_documentation_url</key>
			<string>https://developer.apple.com/documentation/devicemanagement/accounts</string>
			<key>pfm_macos_min</key>
			<string>10.7</string>

2022-02-18 23:43 UTC, kevinmcox approved these changes
Looks good, thanks!

2022-02-23 05:54 UTC, apizz approved these changes
It's funny to me that Apple would have created 2 different preferences that do that are phrased the opposite and yet effectively accomplish the same thing... disable or enable the guest account.

In any case, LGTM.

2022-02-23 05:54 UTC, merged