DigiDNA MCX Wi-Fi Managed correction
ProfileCreator/ProfileManifests pull request #524
Opened 2022-02-14 17:28 UTC by relgit

The Wi-Fi Managed Settings manifest uses an incorrect preference domain when it should just be a subdomain of the greater MCX domain.

This PR renames the manifest file according to convention used on other subdomains of MCX and corrects the information inside the manifest to match. It also contains two minor rewording tweaks.

2022-02-14 20:05 UTC, kevinmcox reviewed
Looks OK to me.

2022-02-15 01:27 UTC, apizz approved these changes

2022-02-15 01:28 UTC, apizz requested changes
Sorry we need a pfm_last_modified update pls & ty

2022-02-15 10:58 UTC, relgit commented
It's buried, but it's there.

2022-02-18 23:42 UTC, kevinmcox approved these changes

2022-02-20 23:45 UTC, Reem502 approved these changes

2022-02-20 23:52 UTC, apizz approved these changes

2022-02-20 23:52 UTC, merged

2022-02-21 00:10 UTC, apizz commented
I don't know who @Reem502 is but given they're a new user and only those who have some role in this project should be able approve or request changes on code review, I've enabled a setting to lock this down.

2022-02-21 08:58 UTC, relgit commented
I don't know either. Perhaps someone who had just joined GitHub as you said and who doesn't yet know their way around the site 🤷‍♂️