Update nl.root3.support.plist
ProfileCreator/ProfileManifests pull request #574
Opened 2022-11-03 09:34 UTC by samuelchchan

Update the manifest to reflect the 6 box in the bottom part instead of 4

2022-11-08 02:30 UTC, apizz requested changes
There's a lot of spacing issues throughout.  Can't accept as is.

<img width="876" alt="Screen Shot 2022-11-07 at 9 29 52 PM" src="https://user-images.githubusercontent.com/11789931/200460461-e3ea418a-1349-4b8f-8225-f606a0d7972e.png">

2022-11-08 02:40 UTC, samuelchchan commented
I've made the change for the spacing, see if this one works

2022-11-09 01:27 UTC, apizz requested changes
In addition to the referenced comments, we need to have the `pfm_last_modified` and `pfm_version` values updated.  This way the apps that use this repo see this latest change.

2022-11-09 01:27 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<key>pfm_type</key>
Can you please add a `pfm_title` for these?  This will end up displaying a more "user friendly" preference name rather than using the actual key name

2022-11-09 01:27 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<string>ex. /Library/Application Support/Your Company/Logo.png</string>
Can you remove the 'ex. ' ?  Just the path is sufficient :)

2022-11-09 01:27 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<key>pfm_value_placeholder</key>
nit-pick: Can you please alphabetize the key ordering here?  keeps things easier to read

2022-11-17 06:12 UTC, samuelchchan commented
I just made another change for it

2022-12-03 21:43 UTC, apizz requested changes

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +	<integer>1.1</integer>
No, this is the actual manifest format version, which ftm should be `1`.  This is not what whould be updated, it's `pfm_version`.  Please review https://github.com/ProfileCreator/ProfileManifests/wiki/Manifest-Format if you have questions about what each of these do.

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
>  		<!-- General -->
Let's just remove this. #567 for reference about why

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<string>Light Mode Logo</string>
fix alphabetical key order

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<string>Dark Mode Logo</string>
fix alphabetical key order

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
> +			<string>Notification Icon</string>
fix alphabetical key order

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
>  		<!-- First Row -->
remove

2022-12-03 21:43 UTC, apizz commented on Manifests/ManagedPreferencesApplications/nl.root3.support.plist
>  		<!-- Second Row -->
Remove

2022-12-18 05:56 UTC, apizz commented
Made these fixes myself to move this along

2022-12-18 05:58 UTC, apizz approved these changes

2022-12-18 05:58 UTC, merged