DigiDNA Nudge updates
ProfileCreator/ProfileManifests pull request #587
Opened 2022-12-19 13:40 UTC by DigiYann

Updated the Nudge Manifest to the latest documented preferencies
Closes #561

2023-01-15 01:06 UTC, apizz requested changes
I'm not sure if you have the pre-commit config installed because this and a few other things should have been caught automatically. 
 Can you please install these? 
 https://github.com/ProfileCreator/ProfileManifests/wiki/Contribute-to-an-Existing-Manifest#2-install--enable-pre-commit

2023-01-15 01:06 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.github.macadmins.Nudge.plist
> +				</dict>
We're missing a pfm_subkeys here to define this as an array of strings.

2023-01-15 01:06 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.github.macadmins.Nudge.plist
> +					<string>false</string>
This should be a boolean false

2023-01-15 01:06 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.github.macadmins.Nudge.plist
> +					<string>false</string>
boolean false

2023-02-20 18:05 UTC, apizz requested changes
I think you're still running into issues because there are a number of errors that _would_ be caught if you had installed the `pre-commit` checks.  Please do this for next time, but I'm going through this now to help get across the finish line

2023-02-20 18:05 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.github.macadmins.Nudge.plist
> +							<key>pfm_name</key>
As this is contained an array, the key name here should actually be `pfm_title`.  `pfm_name` is only used when we have a `<key></key>` and value, and as such wouldn't be in the case of these strings w/in the array.

2023-02-20 18:05 UTC, apizz commented on Manifests/ManagedPreferencesApplications/com.github.macadmins.Nudge.plist
> +							<string>Acceptable Assertion Application Name</string>
Same as previous comment, no `pfm_name` should be here when the main preference is an array.  `pfm_title` is all that's needed besides `pfm_type`

2023-02-22 11:51 UTC, DigiYann commented
Hi AP, thank you for sharing the tool. I have installed it and it rocks. So, do you want to push your correction or should I? I guess that you do following what you wrote (Please do this for next time, but I'm going through this now to help get across the finish line) but keep me posted. Thank you. Best, Y

2023-02-25 16:17 UTC, apizz commented
I forget that your fork branches are protected so I can't contribute back to them to collaborate on PRs like this 🙁 

So if you have the pre-commit setup installed and you bump the last modified date for example it should yell at you with the mis-matched `pfm_default` values.

Lines 245, 320, 336, 352, 368, 404, 436, 683, & 699 should not be `<string>true|false</string>` they should just be either `<true/>` or `<false/>`

2023-02-25 16:18 UTC, apizz commented
That's also in addition to the other comments I made RE not using `pfm_name` in `pfm_subkeys` where the 'parent' preference is an array and subkey is a string

2023-04-09 15:50 UTC, apizz approved these changes

2023-04-09 15:50 UTC, apizz commented
Just moving this across the finish line

2023-04-09 15:50 UTC, merged