DigiDNA March 2023
ProfileCreator/ProfileManifests pull request #607
Opened 2023-03-07 11:58 UTC by DigiYann

* Updated DigiDNA December 2022 to DigiDNA March 2023 
* Updated com.apple.DirectoryService.managed.plist
* Updated com.apple.systemuiserver.plist
* Updated com.apple.finder.plist
* Updated com.apple.desktopservices.plist

2023-03-07 16:15 UTC, DigiYann commented
* Desktopservices: Documentation link (Error 404) has been changed for another
* Nudge: PFC_JSON Preferences File added to SegmentedControl_0, pfm_app_min turned to 1.1.4, pfm_default to true, pfm_description text reworked, added a dictionary for JSON, integer updated to 2 (value)
* AssetCache.managed: pfm_title changed from Share Internet Connection to Disable Caching Over Shared Internet Connection
* DirectoryService.managed: Rework of pfm_conditionals on several keys
* Caldav.account: pfm_note changed
* Finder: pfm_macos_min added
* Loginitems.managed: pfm_documentation_url changed
* Loginwindow: pfm_description changed
* Proxy.http.global: pfm_description changed, pfm_require added, pfm_note chnaged
* Systemuiserver: pfm_description changed, Menu Extras value added to menu bar, dictionary (which was a double) merged from ManagedPreferencesApple to ManifestApple, pfm_title from Allowed Media to Allowed Media and Menu Bar Extras, integer from 4 to 5
* Webcontent-filter: pfm_default from true to false, pfm_note changed

2023-04-09 15:48 UTC, apizz requested changes
Almost there, just a few tweaks.  Thanks for this

2023-04-09 15:48 UTC, apizz commented on Manifests/ManifestsApple/com.apple.caldav.account.plist
> +			<string>An issue resolved with the release of iOS 16 caused the actual default value of this preference on earlier versions of iOS to be false, as opposed to the documented value of true.</string>
Please also update `pfm_last_modified`

2023-04-09 15:48 UTC, apizz commented on Manifests/ManifestsApple/com.apple.systemuiserver.plist
> +			<key>pfm_subkeys</key>
Please sort this alphabetically in the list of keys at the same level, along with all key values within

2023-08-07 19:26 UTC, merged