Added DNS over HTTPS mode & template and policy refresh interval
ProfileCreator/ProfileManifests pull request #620
Opened 2023-05-20 22:29 UTC by northportio

2023-05-21 17:05 UTC, kevinmcox requested changes

2023-05-21 17:05 UTC, kevinmcox commented on Manifests/ManagedPreferencesApplications/com.microsoft.Edge.plist
> +			<string>DNS-over-HTTPS mode</string>
Line 3828 has the same value as 3802.

2023-05-21 17:05 UTC, kevinmcox commented on Manifests/ManagedPreferencesApplications/com.microsoft.Edge.plist
> +		<dict>
Can you sort the `dict` for `PolicyRefreshRate` alphabetically like the other keys please.

2023-08-09 07:29 UTC, relgit approved these changes

2023-08-09 07:37 UTC, merged