Add manifests for Tailscale
ProfileCreator/ProfileManifests pull request #639
Opened 2023-10-31 18:29 UTC by agottardo

This PR adds manifests and icons for both the Mac App Store and Standalone variants of Tailscale for macOS.

2023-11-01 13:43 UTC, apizz requested changes

2023-11-01 16:33 UTC, agottardo commented on Manifests/ManagedPreferencesApplications/io.tailscale.ipn.macos.plist
> +	</array>
done!

2023-11-08 19:29 UTC, apizz reviewed
I think the only ?

2023-11-08 19:29 UTC, apizz commented on Manifests/ManagedPreferencesApplications/io.tailscale.ipn.macos.plist
> +	<string>Configure settings for the Mac App Store variant of the Tailscale client.</string>
Is this really only for the App store version and not also the PKG version of Tailscale?

2023-11-08 19:31 UTC, apizz commented on Manifests/ManagedPreferencesApplications/io.tailscale.ipn.macos.plist
> +	<string>Configure settings for the Mac App Store variant of the Tailscale client.</string>
disregard, I forgot different domains

2023-11-08 19:32 UTC, apizz approved these changes
LGTM! Thanks for contributing ❤️  love when devs contribute to these things :)

2023-11-08 19:32 UTC, merged