Update de.fau.rrze.NetworkShareMounter.plist
ProfileCreator/ProfileManifests pull request #655
Opened 2024-01-30 08:34 UTC by doschupp

With version 3 of the Network Share Mounter, the configuration has changed a little bit and new configuration values are also available.

2024-01-31 02:59 UTC, kevinmcox requested changes
Thanks for the contribution @doschupp.

Please not the pre-commit error:

> Manifests/ManagedPreferencesApplications/de.fau.rrze.NetworkShareMounter.plist: pfm_format_version should be 1, not 2 (https://github.com/ProfileCreator/ProfileManifests/wiki/Manifest-Format-Versions)

Line 14 needs to revert back to `1` while Line 280 needs to be bumped to `2`.

2024-02-15 09:59 UTC, relgit requested changes

2024-02-15 09:59 UTC, relgit commented on Manifests/ManagedPreferencesApplications/de.fau.rrze.NetworkShareMounter.plist
> +			<string>Network shares (Deprecated)</string>
Instead of changing the title to reflect deprecation, could you add the `pfm_app_deprecated` tag to the subkey?

2024-02-15 09:59 UTC, relgit commented on Manifests/ManagedPreferencesApplications/de.fau.rrze.NetworkShareMounter.plist
> +			<key>pfm_default</key>
Please add the `pfm_app_min` to all keys introduced with version 2.

2024-02-26 12:34 UTC, relgit commented on Manifests/ManagedPreferencesApplications/de.fau.rrze.NetworkShareMounter.plist
> +			<key>pfm_default</key>
My bad, I meant to say version 3, though I see that you did that too. Thanks!

2024-02-26 13:08 UTC, relgit commented
I see that the description of the network shares property is also reflecting the deprecation, like the title did, so we need that reverted as well. I'll quickly do that myself so we can merge this with no further delays.

2024-02-26 13:11 UTC, merged