Update Tailscale manifests for v1.60
ProfileCreator/ProfileManifests pull request #658
Opened 2024-02-22 21:54 UTC by agottardo

This PR updates the manifests for Tailscale (App Store and Standalone variants of the client).

- Adds 1 new additional setting for the Mac App Store variant of the client (`KeyExpirationNotice`), and 2 new settings for the Standalone variant (`KeyExpirationNotice` and `UnstableUpdates`). These new settings were released across Tailscale v1.58 and v1.60, and can be managed via MDM.

2024-02-22 23:27 UTC, kevinmcox requested changes
Can you please increment the `pfm_version` at the bottom of each file.

2024-02-23 00:42 UTC, agottardo commented
@kevinmcox done! sorry, I forget every time!

2024-02-25 23:22 UTC, kevinmcox approved these changes
LGTM

2024-02-26 12:31 UTC, relgit approved these changes

2024-02-26 12:31 UTC, merged