New PR to add Elevate24
ProfileCreator/ProfileManifests pull request #708
Opened 2024-09-24 17:13 UTC by liarrmo

Hey, 

Creating a pull request to add Elevate24 to Manifests. Let me know if I need to do anything. First time so apologies in advance! 

Thanks

2024-09-25 07:35 UTC, relgit requested changes
Thanks for the submission @liarrmo. The work you did is already pretty extensive; I just have a handful of requests:

* Apart for the properties from the template, none have default values. This is especially important for boolean ones, but is also useful for others. Please add values using `pfm_default`.
* If a text field has a default value, the placeholder should normally be equal to it. For example, `showAdminPasswordGrace` has a default of `0` so its placeholder should be `0` too.
* Continuing with `showAdminPasswordGrace`, please add a `pfm_range_max` tag equal to `45`.
* Please include a separate icon file in `Icons/ManagedPreferencesApplications/` instead of in `pfm_icon`.
* And lastly, please run the entire manifest through the following command. This will standardize the XML and remove comments: `plutil -convert xml1 com.jigsaw24.Elevate24.plist`.

2024-09-25 08:53 UTC, liarrmo commented
Thank you for the feedback! I’ve resolved all the below, so I will get the changes over. I wanted to ask, we have one bit of configuration which is configured as

<key>microsoftsentinel</key>
<array>
<dict>
<key>SentinelClientId</key>
<string>ClientID</string>
<key>SentinelTennantId</key>
<string>TennantID</string>
<key>SentinelClientsecret</key>
<string>Secret</string>
<key>SentinelUploadURL</key>
<string>URL</string>
</dict>
</array>

Is this possible to represent in the manifest? I can’t see how to do it.

Thanks!


Liam Donnelly | Technical Lead for Workplace Solutions
T: 07711 378 220 | E: ***@***.*** 

L: 
linkedin.com/Jigsaw24 | 
Y: 
youtube.com/WeAreJigsaw24


​​​Please consider the environment - do you really need to print this email?
​​​
​This email may contain confidential information, personal data and/or copyright material and is intended for the use of the addressee only. If you are not the addressee any unauthorised use may be unlawful. If you receive this email by mistake, please advise the sender immediately by using the reply facility in your email software. Any views or opinions presented are those of the sender and do not necessarily represent Jigsaw Systems Limited (trading as Jigsaw24). Jigsaw Systems Limited (2682904) is registered in England and Wales. For further information on our privacy policy please refer to our website. ​Jigsaw24 have taken steps to ensure that this email message and any attachments have been scanned for the presence of viruses, we advise that in keeping with good computing practice the recipient should carry out checks to ensure that they are free of viruses.
 
From: Ari Leviatan ***@***.***>
Date: Wednesday, 25 September 2024 at 08:36
To: ProfileCreator/ProfileManifests ***@***.***>
Cc: Liam Donnelly ***@***.***>, Mention ***@***.***>
Subject: Re: [ProfileCreator/ProfileManifests] New PR to add Elevate24 (PR #708)

CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

@relgit requested changes on this pull request.

Thanks for the submission @liarrmo<https://github.com/liarrmo>. The work you did is already pretty extensive; I just have a handful of requests:

  *   Apart for the properties from the template, none have default values. This is especially important for boolean ones, but is also useful for others. Please add values using pfm_default.
  *   If a text field has a default value, the placeholder should normally be equal to it. For example, showAdminPasswordGrace has a default of 0 so its placeholder should be 0 too.
  *   Continuing with showAdminPasswordGrace, please add a pfm_range_max tag equal to 45.
  *   Please include a separate icon file in Icons/ManagedPreferencesApplications/ instead of in pfm_icon.
  *   And lastly, please run the entire manifest through the following command. This will standardize the XML and remove comments: plutil -convert xml1 com.jigsaw24.Elevate24.plist.

—
Reply to this email directly, view it on GitHub<https://github.com/ProfileCreator/ProfileManifests/pull/708#pullrequestreview-2327388445>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMGS6XM6HVM4CV7XG6CG7Y3ZYJRXBAVCNFSM6AAAAABOYYTIX6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRXGM4DQNBUGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-25 11:14 UTC, relgit commented
Yes. The following is a stripped-down example you can build on. It will appear as a multi-column table.
```xml
...
<dict>
    <key>pfm_name</key>
    <string>microsoftsentinel</string>
    <key>pfm_subkeys</key>
    <array>
        <dict>
            <key>pfm_name</key>
            <string>microsoftsentinelItem</string>
            <key>pfm_subkeys</key>
            <array>
                <dict>
                    <key>pfm_name</key>
                    <string>SentinelClientId</string>
                    <key>pfm_type</key>
                    <string>string</string>
                </dict>
                <dict>
                    <key>pfm_name</key>
                    <string>SentinelTennantId</string>
                    <key>pfm_type</key>
                    <string>string</string>
                </dict>
                ...
            </array>
            <key>pfm_type</key>
            <string>dictionary</string>
        </dict>
    </array>
    <key>pfm_type</key>
    <string>array</string>
</dict>
...
```

2024-09-25 13:13 UTC, liarrmo commented
Appreciate it, thank you! I've made all the changes and looks good from my end. Let me know if I have missed anything off?

2024-09-26 09:29 UTC, relgit commented
Thanks for making the requested changes.

Looks like you followed all of the advice, but there's a small confusion about value types. These should be of the same type as that of the property. This applies to values of `pfm_default` and `pfm_range_max` so for example, a boolean property default value could be `<false/>` or `<true/>`, and an integer's `<integer>45</integer>`.

You did mention it was your first manifest 😀

By the way, this does not apply to `pfm_value_placeholder` which represents text and therefore must always be `string`.

2024-09-26 10:36 UTC, liarrmo commented
Well that makes perfect sense now! Thank you so much for your help with this, I've made those changes now

2024-09-26 15:07 UTC, relgit requested changes
Alright last two comments and we're done.

2024-09-26 15:07 UTC, relgit commented on Manifests/ManagedPreferencesApplications/com.jigsaw24.Elevate24.plist
> +			<string>Mainbutton Txt (Premium)</string>
Let's change "Mainbutton Txt" to "Main Button Text".

2024-09-26 15:07 UTC, relgit commented on Manifests/ManagedPreferencesApplications/com.jigsaw24.Elevate24.plist
> +			<string>0</string>
This value should also be of type integer.

2024-09-26 15:23 UTC, liarrmo commented
Thanks, good spot. All sorted. Appreciate it!

2024-09-26 15:54 UTC, merged